name: "Best practice test"

on:
  pull_request:

jobs:
  jira-issue:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v3
      - name: PR title contains Jira ticket
        run: if [ -z $(grep -Eo "[A-Z][A-Z0-9]+-[0-9]+" <<< "${{ github.event.pull_request.title }}") ]; then echo "PR title should contain a Jira."; else echo "Well done!"; fi
        shell: bash
      - name: Commits contain Jira ticket
        run: |
          UNMERGED_COMMITS=$(git cherry -v "$GITHUB_BASE_REF" "${{ github.ref_name }}")
          while read line; do
            if [ -z $(grep -Eo "[A-Z][A-Z0-9]+-[0-9]+" <<< "$line") ]; then echo "Commit message '$line' should contain a Jira."; fi
          done < echo $UNMERGED_COMMITS
        shell: bash
      - name: PR description is not empty
        run: if [ -z "${{ github.event.pull_request.body}}" ]; then echo "The PR needs a non-empty description."; else echo "Well done!";  fi
